### ISSUE TITLE
are you going to release the pretrained model

### ISSUE THREAD

**Issue by wangzheallen** [ppwwyyxx/GroupNorm-reproduce#1]

**Comment by ppwwyyxx** [comment]
There is a pretrained ResNet50 at https://github.com/ppwwyyxx/GroupNorm-reproduce/tree/master/ImageNet-ResNet-TensorFlow and pretrained ResNet50 & ResNet101 at https://github.com/facebookresearch/Detectron/tree/master/projects/GN
