### ISSUE TITLE
Resnet 101 GN Pretrained

### ISSUE THREAD

**Issue by erichhhhho** [ppwwyyxx/GroupNorm-reproduce#4]
Hi,

Is it possible or did you try training the resnet101 on ImageNet? Could you release the pretrained weights?

Thx

**Comment by ppwwyyxx** [comment]
Both the official caffe2 link and the tensorflow implementation in this repo contain a ResNet101 model.

**Comment by hongnianwang** [comment]
Hi,

Is it possible or did you try training the resnet18 or 34 on ImageNet? Could you release the pretrained weights?

Thx

**Comment by ppwwyyxx** [comment]
There is no resnet18 or 34.
