### ISSUE TITLE
How to run detection on any custom image

### ISSUE THREAD

**Issue by spaul13** [ppwwyyxx/GroupNorm-reproduce#5]
using the pretrained models, how can I run detection on any image?

**_python imagenet-resnet-gn.py --data C:\yolo\resnet\GroupNorm-reproduce\ImageNet-ResNet-TensorFlow\image\ -d 101 --eval --load ImageNet-R101-GroupNorm32-AlignPadding.npz_**

In the image folder I have .png files on which I want to perform detection. But it keeps on giving the error of

 _File "imagenet-resnet-gn.py", line 128, in <module>
    ds = get_imagenet_dataflow(args.data, 'val', batch)
  File "C:\yolo\resnet\GroupNorm-reproduce\ImageNet-ResNet-TensorFlow\imagenet_utils.py", line 95, in get_imagenet_dataflow
    ds = dataset.ILSVRC12Files(datadir, name, shuffle=False)
  File "C:\Users\paul90\AppData\Local\Continuum\anaconda3\envs\yolov3\lib\site-packages\tensorpack\dataflow\dataset\ilsvrc.py", line 164, in __init__
    assert os.path.isfile(fname), fname
AssertionError: C:\yolo\resnet\GroupNorm-reproduce\ImageNet-ResNet-TensorFlow\image\val\ILSVRC2012_val_00000001.JPEG_

can anyone please tell me how to run the detection on any image?

**Comment by ppwwyyxx** [comment]
The model is not a detection model. It is a classification model.

The code does not include functions to run model on any given image. To implement this, please see [tensorpack documentation](https://tensorpack.readthedocs.io/tutorial/inference.html#inference-after-training-what-tensorpack-does).
